export type ContestStatus = 'open' | 'soon' | 'closed';
export type ContestLevel = 'medium' | 'superior';
export type ContestCategory = 'police' | 'fiscal' | 'admin' | 'legal' | 'health' | 'education';
export type EducationLevel = 'fundamental' | 'medium' | 'superior' | 'pos';

export type Contest = {
  id: string;
  institution: string;
  role: string;
  salary: string;
  status: ContestStatus;
  level: ContestLevel;
  category: ContestCategory;
  requirements: {
    minAge?: number;
    maxAge?: number;
    education: EducationLevel;
    requiresCNH: boolean;
    requiresTAF: boolean;
    customText: string;
  };
  details: {
    vacancies: string;
    requirements: string;
    link: string;
    registrationPeriod?: string;
    examDate?: string;
  };
};

export const CONTESTS: Contest[] = [
  // --- NÍVEL MÉDIO ---
  {
    id: 'ibge-supervisor',
    institution: 'IBGE',
    role: 'Supervisor de Coleta e Qualidade',
    salary: 'R$ 3.379,00',
    status: 'open',
    level: 'medium',
    category: 'admin',
    requirements: {
      education: 'medium',
      requiresCNH: true,
      requiresTAF: false,
      customText: 'Ensino Médio completo e CNH categoria B definitiva.',
    },
    details: {
      vacancies: '150 vagas',
      requirements: 'Ensino Médio completo e CNH categoria B definitiva.',
      link: 'https://www.pciconcursos.com.br/noticias/ibge-abre-processos-seletivos-com-mais-de-9-mil-vagas',
      registrationPeriod: '19/11/2025 a 17/12/2025',
      examDate: '22/02/2026',
    },
  },
  {
    id: 'ibge-agente',
    institution: 'IBGE',
    role: 'Agente de Pesquisas e Mapeamento',
    salary: 'R$ 1.512,00',
    status: 'open',
    level: 'medium',
    category: 'admin',
    requirements: {
      education: 'medium',
      requiresCNH: false,
      requiresTAF: false,
      customText: 'Ensino Médio completo.',
    },
    details: {
      vacancies: '500 vagas',
      requirements: 'Ensino Médio completo.',
      link: 'https://www.pciconcursos.com.br/noticias/ibge-abre-processos-seletivos-com-mais-de-9-mil-vagas',
      registrationPeriod: '19/11/2025 a 17/12/2025',
      examDate: '22/02/2026',
    },
  },
  {
    id: 'pm-soldado',
    institution: 'Polícia Militar',
    role: 'Soldado 2ª Classe',
    salary: 'R$ 4.852,21',
    status: 'soon',
    level: 'medium',
    category: 'police',
    requirements: {
      education: 'medium',
      minAge: 17,
      maxAge: 30,
      requiresCNH: true,
      requiresTAF: true,
      customText: 'Nível Médio, 17 a 30 anos, Altura min 1.60m.',
    },
    details: {
      vacancies: '500 vagas',
      requirements: 'Nível médio completo, idade entre 17 e 30 anos, altura mínima de 1,65m para homens e 1,60m para mulheres.',
      link: 'https://www.pciconcursos.com.br',
      registrationPeriod: 'A definir',
      examDate: 'A definir',
    },
  },
  {
    id: 'caixa-tecnico',
    institution: 'Caixa Econômica Federal',
    role: 'Técnico Bancário',
    salary: 'R$ 5.200,00',
    status: 'open',
    level: 'medium',
    category: 'admin',
    requirements: {
      education: 'medium',
      requiresCNH: false,
      requiresTAF: false,
      customText: 'Nível médio completo, conhecimentos em matemática e português.',
    },
    details: {
      vacancies: '300 vagas',
      requirements: 'Nível médio completo, conhecimentos em matemática e português.',
      link: 'https://www.pciconcursos.com.br',
      registrationPeriod: '15/01/2024 a 15/02/2024',
      examDate: '10/04/2024',
    },
  },
  {
    id: 'pf-admin',
    institution: 'Polícia Federal',
    role: 'Agente Administrativo',
    salary: 'R$ 4.746,16',
    status: 'open',
    level: 'medium',
    category: 'admin',
    requirements: {
      education: 'medium',
      requiresCNH: false,
      requiresTAF: false,
      customText: 'Nível Médio completo.',
    },
    details: {
      vacancies: '50 vagas',
      requirements: 'Diploma de nível médio completo, idade entre 18 e 50 anos.',
      link: 'https://www.pciconcursos.com.br',
      registrationPeriod: '01/03/2024 a 31/03/2024',
      examDate: '15/06/2024',
    },
  },
  // --- NÍVEL SUPERIOR ---
  {
    id: 'pc-sc-agente',
    institution: 'Polícia Civil (PC-SC)',
    role: 'Agente de Polícia',
    salary: 'R$ 5.290,95',
    status: 'open',
    level: 'superior',
    category: 'police',
    requirements: {
      education: 'superior',
      requiresCNH: true,
      requiresTAF: true,
      customText: 'Nível Superior em qualquer área + CNH B.',
    },
    details: {
      vacancies: '80 vagas',
      requirements: 'Nível Superior em qualquer área, CNH categoria B, teste de aptidão física.',
      link: 'https://www.pciconcursos.com.br',
      registrationPeriod: '10/02/2024 a 10/03/2024',
      examDate: '20/05/2024',
    },
  },
  {
    id: 'aft-auditor',
    institution: 'Ministério do Trabalho',
    role: 'Auditor Fiscal do Trabalho',
    salary: 'R$ 22.921,71',
    status: 'closed',
    level: 'superior',
    category: 'fiscal',
    requirements: {
      education: 'superior',
      requiresCNH: false,
      requiresTAF: false,
      customText: 'Nível Superior em qualquer área.',
    },
    details: {
      vacancies: '150 vagas',
      requirements: 'Diploma de nível superior em qualquer área.',
      link: 'https://www.pciconcursos.com.br',
      registrationPeriod: 'Encerrado',
      examDate: 'Realizado',
    },
  },
  {
    id: 'tj-analista',
    institution: 'Tribunal de Justiça',
    role: 'Analista Judiciário',
    salary: 'R$ 12.500,00',
    status: 'open',
    level: 'superior',
    category: 'legal',
    requirements: {
      education: 'superior',
      requiresCNH: false,
      requiresTAF: false,
      customText: 'Diploma de nível superior em Direito, registro na OAB.',
    },
    details: {
      vacancies: '80 vagas',
      requirements: 'Diploma de nível superior em Direito, registro na OAB.',
      link: 'https://www.pciconcursos.com.br',
      registrationPeriod: '01/04/2024 a 30/04/2024',
      examDate: '25/07/2024',
    },
  },
  {
    id: 'receita-auditor',
    institution: 'Receita Federal',
    role: 'Auditor Fiscal',
    salary: 'R$ 22.000,00',
    status: 'open',
    level: 'superior',
    category: 'fiscal',
    requirements: {
      education: 'superior',
      requiresCNH: false,
      requiresTAF: false,
      customText: 'Diploma de nível superior em Direito, Economia, Contabilidade ou Administração.',
    },
    details: {
      vacancies: '150 vagas',
      requirements: 'Diploma de nível superior em Direito, Economia, Contabilidade ou Administração.',
      link: 'https://www.pciconcursos.com.br',
      registrationPeriod: '05/03/2024 a 05/04/2024',
      examDate: '30/06/2024',
    },
  },
  {
    id: 'bcb-analista',
    institution: 'Banco Central do Brasil',
    role: 'Analista',
    salary: 'R$ 20.924,80',
    status: 'open',
    level: 'superior',
    category: 'fiscal',
    requirements: {
      education: 'superior',
      requiresCNH: false,
      requiresTAF: false,
      customText: 'Diploma de nível superior em qualquer área, conhecimento em economia, direito ou administração.',
    },
    details: {
      vacancies: '200 vagas',
      requirements: 'Diploma de nível superior em qualquer área, conhecimento em economia, direito ou administração.',
      link: 'https://www.pciconcursos.com.br',
      registrationPeriod: '10/02/2024 a 10/03/2024',
      examDate: '20/05/2024',
    },
  },
  {
    id: 'saude-enfermeiro',
    institution: 'Ministério da Saúde',
    role: 'Técnico em Enfermagem',
    salary: 'R$ 3.800,00',
    status: 'open',
    level: 'medium',
    category: 'health',
    requirements: {
      education: 'medium',
      requiresCNH: false,
      requiresTAF: false,
      customText: 'Diploma de nível médio em Técnico de Enfermagem, registro no COREN.',
    },
    details: {
      vacancies: '120 vagas',
      requirements: 'Diploma de nível médio em Técnico de Enfermagem, registro no COREN.',
      link: 'https://www.pciconcursos.com.br',
      registrationPeriod: '20/02/2024 a 20/03/2024',
      examDate: '18/05/2024',
    },
  },
  {
    id: 'educacao-professor',
    institution: 'Secretaria de Educação',
    role: 'Professor de Matemática',
    salary: 'R$ 6.500,00',
    status: 'open',
    level: 'superior',
    category: 'education',
    requirements: {
      education: 'superior',
      requiresCNH: false,
      requiresTAF: false,
      customText: 'Diploma de nível superior em Licenciatura em Matemática ou áreas afins.',
    },
    details: {
      vacancies: '200 vagas',
      requirements: 'Diploma de nível superior em Licenciatura em Matemática ou áreas afins.',
      link: 'https://www.pciconcursos.com.br',
      registrationPeriod: '10/03/2024 a 10/04/2024',
      examDate: '22/06/2024',
    },
  },
  {
    id: 'tce-analista',
    institution: 'Tribunal de Contas',
    role: 'Analista de Controle Externo',
    salary: 'R$ 15.000,00',
    status: 'open',
    level: 'superior',
    category: 'fiscal',
    requirements: {
      education: 'superior',
      requiresCNH: false,
      requiresTAF: false,
      customText: 'Diploma de nível superior em qualquer área, preferência para Direito, Contabilidade ou Administração.',
    },
    details: {
      vacancies: '60 vagas',
      requirements: 'Diploma de nível superior em qualquer área, preferência para Direito, Contabilidade ou Administração.',
      link: 'https://www.pciconcursos.com.br',
      registrationPeriod: '01/05/2024 a 31/05/2024',
      examDate: '15/08/2024',
    },
  },
  {
    id: 'prefeitura-admin',
    institution: 'Prefeitura Municipal',
    role: 'Agente Administrativo',
    salary: 'R$ 3.500,00',
    status: 'open',
    level: 'medium',
    category: 'admin',
    requirements: {
      education: 'medium',
      requiresCNH: false,
      requiresTAF: false,
      customText: 'Nível médio completo, conhecimentos básicos em informática.',
    },
    details: {
      vacancies: '100 vagas',
      requirements: 'Nível médio completo, conhecimentos básicos em informática.',
      link: 'https://www.pciconcursos.com.br',
      registrationPeriod: '15/04/2024 a 15/05/2024',
      examDate: '10/07/2024',
    },
  },
  // --- MAIS CONCURSOS BASEADOS NO PCI CONCURSOS ---
  {
    id: 'trf4-analista',
    institution: 'TRF4 - Tribunal Regional Federal',
    role: 'Analista Judiciário',
    salary: 'R$ 11.500,00',
    status: 'open',
    level: 'superior',
    category: 'legal',
    requirements: {
      education: 'superior',
      requiresCNH: false,
      requiresTAF: false,
      customText: 'Nível Superior em qualquer área. Para área jurídica: Direito e OAB.',
    },
    details: {
      vacancies: '120 vagas',
      requirements: 'Nível Superior em qualquer área. Para área jurídica: Direito e registro na OAB.',
      link: 'https://www.pciconcursos.com.br',
      registrationPeriod: '05/05/2024 a 05/06/2024',
      examDate: '28/07/2024',
    },
  },
  {
    id: 'inss-tecnico',
    institution: 'INSS - Instituto Nacional do Seguro Social',
    role: 'Técnico do Seguro Social',
    salary: 'R$ 6.000,00',
    status: 'soon',
    level: 'medium',
    category: 'admin',
    requirements: {
      education: 'medium',
      requiresCNH: false,
      requiresTAF: false,
      customText: 'Nível médio completo.',
    },
    details: {
      vacancies: '1.000 vagas',
      requirements: 'Nível médio completo.',
      link: 'https://www.pciconcursos.com.br',
      registrationPeriod: 'A definir',
      examDate: 'A definir',
    },
  },
  {
    id: 'prf-policial',
    institution: 'PRF - Polícia Rodoviária Federal',
    role: 'Policial Rodoviário Federal',
    salary: 'R$ 8.500,00',
    status: 'soon',
    level: 'superior',
    category: 'police',
    requirements: {
      education: 'superior',
      minAge: 18,
      maxAge: 40,
      requiresCNH: true,
      requiresTAF: true,
      customText: 'Nível Superior, CNH B, 18 a 40 anos, altura mínima 1,60m.',
    },
    details: {
      vacancies: '500 vagas',
      requirements: 'Nível Superior em qualquer área, CNH categoria B, idade entre 18 e 40 anos, altura mínima de 1,60m.',
      link: 'https://www.pciconcursos.com.br',
      registrationPeriod: 'A definir',
      examDate: 'A definir',
    },
  },
  {
    id: 'tse-analista',
    institution: 'TSE - Tribunal Superior Eleitoral',
    role: 'Analista Judiciário',
    salary: 'R$ 13.200,00',
    status: 'open',
    level: 'superior',
    category: 'admin',
    requirements: {
      education: 'superior',
      requiresCNH: false,
      requiresTAF: false,
      customText: 'Nível Superior em qualquer área.',
    },
    details: {
      vacancies: '80 vagas',
      requirements: 'Nível Superior em qualquer área.',
      link: 'https://www.pciconcursos.com.br',
      registrationPeriod: '01/06/2024 a 30/06/2024',
      examDate: '25/08/2024',
    },
  },
  {
    id: 'anac-especialista',
    institution: 'ANAC - Agência Nacional de Aviação Civil',
    role: 'Especialista em Regulação',
    salary: 'R$ 18.500,00',
    status: 'open',
    level: 'superior',
    category: 'fiscal',
    requirements: {
      education: 'superior',
      requiresCNH: false,
      requiresTAF: false,
      customText: 'Nível Superior em Engenharia, Direito, Economia ou áreas afins.',
    },
    details: {
      vacancies: '40 vagas',
      requirements: 'Nível Superior em Engenharia, Direito, Economia ou áreas afins.',
      link: 'https://www.pciconcursos.com.br',
      registrationPeriod: '10/05/2024 a 10/06/2024',
      examDate: '15/08/2024',
    },
  },
  {
    id: 'ans-tecnico',
    institution: 'ANS - Agência Nacional de Saúde Suplementar',
    role: 'Técnico em Regulação',
    salary: 'R$ 7.200,00',
    status: 'open',
    level: 'medium',
    category: 'health',
    requirements: {
      education: 'medium',
      requiresCNH: false,
      requiresTAF: false,
      customText: 'Nível médio completo.',
    },
    details: {
      vacancies: '60 vagas',
      requirements: 'Nível médio completo.',
      link: 'https://www.pciconcursos.com.br',
      registrationPeriod: '20/05/2024 a 20/06/2024',
      examDate: '10/08/2024',
    },
  },
  {
    id: 'abin-agente',
    institution: 'ABIN - Agência Brasileira de Inteligência',
    role: 'Agente de Inteligência',
    salary: 'R$ 9.800,00',
    status: 'soon',
    level: 'superior',
    category: 'police',
    requirements: {
      education: 'superior',
      minAge: 18,
      maxAge: 45,
      requiresCNH: true,
      requiresTAF: true,
      customText: 'Nível Superior, CNH B, 18 a 45 anos, aptidão física e psicológica.',
    },
    details: {
      vacancies: '100 vagas',
      requirements: 'Nível Superior em qualquer área, CNH categoria B, idade entre 18 e 45 anos, aptidão física e psicológica.',
      link: 'https://www.pciconcursos.com.br',
      registrationPeriod: 'A definir',
      examDate: 'A definir',
    },
  },
  {
    id: 'tcu-auditor',
    institution: 'TCU - Tribunal de Contas da União',
    role: 'Auditor Federal de Controle Externo',
    salary: 'R$ 19.500,00',
    status: 'open',
    level: 'superior',
    category: 'fiscal',
    requirements: {
      education: 'superior',
      requiresCNH: false,
      requiresTAF: false,
      customText: 'Nível Superior em qualquer área.',
    },
    details: {
      vacancies: '50 vagas',
      requirements: 'Nível Superior em qualquer área.',
      link: 'https://www.pciconcursos.com.br',
      registrationPeriod: '15/05/2024 a 15/06/2024',
      examDate: '20/08/2024',
    },
  },
  {
    id: 'mpe-promotor',
    institution: 'MPE - Ministério Público Estadual',
    role: 'Promotor de Justiça',
    salary: 'R$ 24.000,00',
    status: 'soon',
    level: 'superior',
    category: 'legal',
    requirements: {
      education: 'superior',
      requiresCNH: false,
      requiresTAF: false,
      customText: 'Nível Superior em Direito, OAB com no mínimo 3 anos de exercício.',
    },
    details: {
      vacancies: '30 vagas',
      requirements: 'Nível Superior em Direito, registro na OAB há pelo menos 3 anos.',
      link: 'https://www.pciconcursos.com.br',
      registrationPeriod: 'A definir',
      examDate: 'A definir',
    },
  },
  {
    id: 'sefaz-fiscal',
    institution: 'SEFAZ - Secretaria da Fazenda',
    role: 'Auditor Fiscal',
    salary: 'R$ 14.500,00',
    status: 'open',
    level: 'superior',
    category: 'fiscal',
    requirements: {
      education: 'superior',
      requiresCNH: false,
      requiresTAF: false,
      customText: 'Nível Superior em Contabilidade, Direito, Economia ou Administração.',
    },
    details: {
      vacancies: '200 vagas',
      requirements: 'Nível Superior em Contabilidade, Direito, Economia ou Administração.',
      link: 'https://www.pciconcursos.com.br',
      registrationPeriod: '01/06/2024 a 01/07/2024',
      examDate: '15/09/2024',
    },
  },
  {
    id: 'cagepa-tecnico',
    institution: 'CAGEPA - Companhia de Água e Esgotos',
    role: 'Técnico de Saneamento',
    salary: 'R$ 4.200,00',
    status: 'open',
    level: 'medium',
    category: 'admin',
    requirements: {
      education: 'medium',
      requiresCNH: false,
      requiresTAF: false,
      customText: 'Nível médio completo.',
    },
    details: {
      vacancies: '80 vagas',
      requirements: 'Nível médio completo.',
      link: 'https://www.pciconcursos.com.br',
      registrationPeriod: '10/05/2024 a 10/06/2024',
      examDate: '05/08/2024',
    },
  },
  {
    id: 'detran-agente',
    institution: 'DETRAN - Departamento de Trânsito',
    role: 'Agente de Trânsito',
    salary: 'R$ 4.800,00',
    status: 'open',
    level: 'medium',
    category: 'police',
    requirements: {
      education: 'medium',
      requiresCNH: true,
      requiresTAF: true,
      customText: 'Nível médio completo, CNH B, aptidão física.',
    },
    details: {
      vacancies: '150 vagas',
      requirements: 'Nível médio completo, CNH categoria B, teste de aptidão física.',
      link: 'https://www.pciconcursos.com.br',
      registrationPeriod: '15/05/2024 a 15/06/2024',
      examDate: '12/08/2024',
    },
  },
];

